version: '3.8'  
  
services:  
  frontend-prod:
    image: cocopam/captcha-front:latest  
    deploy:  
      placement:
        constraints: [node.labels.env == prod]
      restart_policy:  
        condition: on-failure  

    networks:  
      - traefik-network  
  frontend-dev:  
    image: cocopam/captcha-front:latest  
    ports:
      - "5600:80"
    deploy:  
      placement:
        constraints: [node.labels.env == dev]
      restart_policy:  
        condition: on-failure  
    networks:  
      - traefik-network
  
networks:  
  traefik-network:  
    external: true  
