version: '3.8'  
  
services:  
  frontend:  
    image: cocopam/captcha-front:latest  
    ports:
      - "5600:80"
    deploy:  
      placement:
        constraints: [node.labels.env == dev]
      restart_policy:  
        condition: on-failure  
