version: '3.8'  
  
services:  
  nginx:
    image: nginx:stable-alpine-slim
    deploy:  
      placement:
        constraints: [node.role == manager and node.labels.ingress == true]
      restart_policy:
        condition: on-failure
      replicas: 1   
    volumes:
      - ./ingress/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 6000
    networks:
      - traefik-network


networks:
  traefik-network:
    driver: overlay
    external: true