version: '3.8'  
  
services:  
  backend:
    image: cocopam/captcha-server:latest  
    deploy:  
      replicas: 2
      placement:
        constraints: [node.labels.env == prod]
      restart_policy:  
        condition: on-failure  
    networks:  
      - traefik-network  