version: '3.8'  
  
services:  
  backend:
    image: cocopam/captcha-server:latest  
    ports:
      - "5601:8000"
    deploy:  
      replicas: 1
      placement:
        constraints: [node.labels.env == dev]
      restart_policy:  
        condition: on-failure   

