version: '3.8'  
  
services:  
  backend-prod:
    name: captcha_backend_prod
    image: cocopam/captcha-server:latest  
    deploy:  
      replicas: 2
      placement:
        constraints: [node.labels.env == prod]
      restart_policy:  
        condition: on-failure  
    networks:  
      - traefik-network  
  backend-dev:
    image: cocopam/captcha-server:latest
    ports:
      - "5601:8000"
    deploy:
      placement:
        constraints: [node.labels.env == dev]
      restart_policy:  
        condition: on-failure  
    networks:  
      - traefik-network  
networks:  
  traefik-network:  
    external: true 
