version: '3.8'

services:
  traefik:
    image: traefik:v3.3.4
    deploy:  
      replicas: 1  
    command:
      - "--providers.docker"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.be.address=:8001"       # BE용 엔트리포인트
      - "--api.dashboard=true"
      - "--api.insecure=true"
    ports:
      - "80:80"
      - "8080:8080"
      - "8081:8081"        # Dashboard
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - traefik-network

networks:
  traefik-network:
    driver: overlay
    external: true