version: '3.8'

services:
  backend:
    image: cocopam/captcha-server:latest
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.env == dev]
      restart_policy:
        condition: on-failure
    networks:
      - traefik-network

  frontend:
    image: cocopam/captcha-front:latest
    deploy:
      placement:
        constraints: [node.labels.env == dev]
      restart_policy:
        condition: on-failure
    networks:
      - traefik-network


networks:
  traefik-network:
    driver: overlay
    external: true 