version: '3.8'

services:
  backend:
    image: cocopam/captcha-server:latest
    environment:
      - REMOTE_ML_SERVICE_URL=http://mlflow:5000
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.env == prod]
      restart_policy:
        condition: on-failure
    networks:
      - traefik-network

  frontend:
    image: cocopam/captcha-front:latest
    ports:
      - target: 80
        published: 5001
    deploy:
      placement:
        constraints: [node.labels.fe == true]
      restart_policy:
        condition: on-failure
    networks:
      - traefik-network

  mlflow:
    image: bitnami/mlflow:2.22.0
    ports:
      - target: 5000
        published: 5000
    deploy:
      replicas: 1
      placement:
        constraints: [node.labels.ml == true]
      restart_policy:
        condition: on-failure
    volumes:
      - mlflow-artifacts:/app/mlruns
    networks:
      - traefik-network
    working_dir: /app
    entrypoint: >
      mlflow server
      --host 0.0.0.0
      --port 5000

  nginx:
    image: nginx:stable-alpine-slim
    deploy:
      placement:
        constraints: [node.labels.ingress == true]
      restart_policy:
        condition: on-failure
      replicas: 1
    volumes:
      - ./ingress/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - target: 80
        published: 8002
    networks:
      - traefik-network

networks:
  traefik-network:
    driver: overlay
    external: true 
volumes:
  mlflow-artifacts:
 
