version: '3.8'

services:
  nginx:
    image: nginx:latest
    deploy:  
      placement:
        constraints: [node.role == manager]
      restart_policy:
        condition: on-failure
      replicas: 1   
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "6000:80"         # FE entry point
    networks:
      - traefik-network

networks:
  traefik-network:
    driver: overlay
    external: true